[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.17.0"
  NPM_VERSION = "10"
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200